[package]
name = "dohee-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
dohee-tools = { path = "../dohee-tools" }
async-trait = { workspace = true }
tokio = { workspace = true }
