[package]
name = "dohee-infer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
vulkan = ["llama-cpp-2/vulkan"]
cuda = ["llama-cpp-2/cuda"]

[dependencies]
llama-cpp-2 = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
